version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "5000:5000"
    command: sleep infinity
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_DB_NAME=library
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
    network_mode:
      - service:mongo
      - service:redis
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/mongo
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data/redis

volumes:
  mongodb-data:
  redis-data:
